### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by PandoricGalaxy** [Passive/Cleo#20]
Hello, I am having an issue with (Compilation).

Errors: (None).

I am running Windows version (10 Pro) and my specs are (CPU i5-4310 2c4t)

I am new to this compilation and idk how to compile this;
ive searched for tutorials and solutions but i am unable to find help

In order to reproduce this problem you must, (not compile).

**Comment by Passive** [comment]
Install vcpkg, run the install_dependencies script and then setup a new Visual Studio solution. Adjust project properties (disable debugging information, set c++ standard to 17 or greater and make sure you configure your project to use static vcpkg libraries.

Compile in x86 Release. Any further issues just let me know.

**Comment by PandoricGalaxy** [comment]
Do i have to use visual studio 2019 or visual studio code?

**Comment by PandoricGalaxy** [comment]
I have done all that now,
I opened new blank solution and did all that
But don't I need to like import .h and .cpp files from cleo to this project? I mean cause I didn't do it and idk how to do it

**Comment by Passive** [comment]
Yes. You need to import the files provided in the repository into your solution.

**Comment by PandoricGalaxy** [comment]
> Yes. You need to import the files provided in the repository into your solution.

How to import it?

**Comment by Passive** [comment]
You should not be trying to use this if you don't know how to import files into Visual Studio. Stop wasting my time.
